============
Basic Struct
============
struct Point {
	float x;
	float y;
};
---
(source_file
	(statement
		(type_def
			(struct_def
				(identifier)
				(maybe_type_field
					(type_field
						(type
							(type_identifier
								(identifier)))
						(specialised_field
							(identifier))))
				(maybe_type_field
					(type_field
						(type
							(type_identifier
								(identifier)))
						(specialised_field
									(identifier))))))))
